name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the jobify repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure Git user
        run: |
          git config --global user.name "btkcodedev"
          git config --global user.email "btk.codedev@gmail.com"

      - name: Update submodules to the latest commit
        run: |
          git submodule update --remote
          git add .
          git commit -m "Update submodules to latest commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
